import Header from '@/modules/header';
import PageManager from '@/modules/page-manager';
import Head from 'next/head';

const HeaderNavs = [
  {id: 1, name: 'Home', tag: 'home'},
  {
    id: 2,
    name: 'Skills',
    tag: 'skills',
  },
  {
    id: 3,
    name: 'Work Experiences',
    tag: 'work-experiences',
  },

  {
    id: 4,
    name: 'Projects',
    tag: 'projects',
  },
  {
    id: 5,
    name: 'Contact me',
    tag: 'contact-me',
  },
];

export default function Home() {
  return (
    <div className="h-full bg-primary-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerNavs={HeaderNavs} />
      <PageManager />
    </div>
  );
}
